version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: ../docker/frontend.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api-server
  
  api-server:
    build: 
      context: ./api-server
      dockerfile: ../docker/api.dockerfile
    ports:
      - "5000:5000"
    environment: